### PR TITLE
add tls - draft

### PR DESCRIPTION
**Pull request by adrianadrianadrianadrianadrian**

### CODE REVIEW

**Review by lulf — COMMENTED** [review]
Wow 🚀 Thanks for working on this!

I like the structure of it. I am wondering if you could make the TlsConfig "config" (currently ClientConfig) field be a generic type, and have the type be dictated by an associated type on the Transport? The reason is that you could have an OpenSSL-based version later, or something else for embedded use cases for instance.

**Comment by adrianadrianadrianadrianadrian** [comment]
Yeah agreed, though I might go a bit further on that thought. I'll put up another change and get your feedback on it shortly. Admittedly, this branch was the quick and dirty approach.

**Comment by adrianadrianadrianadrianadrian** [comment]
@lulf thoughts on this approach? It allows for any ssl/tls we'd want.

**Review by lulf — COMMENTED** [review]
Sorry for the late response, thank you for working on this and your patience :)

I think the readability of this variant suffers a bit. I think maybe the Stream, ToTcp, FromTcp  traits, although elegant, adds some cognitive load. There is already the Network trait which I think we should adopt and use.

I would like to keep S: ToSocketAddrs, as it feels more 'rust native'.

I wonder if an alternative would something like:

```
trait TlsProvider {
   type Config: Default;
   type Input: Network;
   type Output: Network;
   fn wrap(stream: Self::Input, config: Self::Config) -> Self::Output;
}

struct NoTls;
impl TlsProvider for NoTls {
   type Config = ();
   type Input = MioNetwork;
   type Output = MioNetwork; 
   fn wrap(stream: Self::Input, config: Self::Config) -> Self::Output {
      stream
   }
}
```

Apologies in advance for any edge cases I have not considered!

**Comment by catch-twenty-two** [comment]
Does this pr enable a connection to Azure Services? @adrianadrianadrianadrianadrian were you able to get this successfully implemented?

**Comment by adrianadrianadrianadrianadrian** [comment]
@catch-twenty-two Yeah this PR allows one to connect to ServiceBus/EventHubs, however I'd go down the route of Kafka for EventHubs (https://www.adrians-blog.com/articles/software/2021/12/08/azure-eventhubs-in-rust/) and Ntex-amqp (https://github.com/ntex-rs/ntex-amqp) for ServiceBus. 

I had the most success with the above. Unfortunately I kept running into more and more subtle issues with this library, specifically when consuming off EventHubs; that's not to say the library is bad, just I hadn't invested enough time to get it working reliably. 

I'll close this PR off. Cheers all.

**Pull request closed without merging**
